# Generated by Django 4.2.23 on 2025-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('poste', models.CharField(blank=True, max_length=100)),
                ('structure', models.CharField(blank=True, max_length=100)),
                ('site', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_engagement', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
